name: Update Google Scholar stats

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 2 * * *"  # runs at 02:00 UTC daily
  workflow_dispatch:     # allows manual runs from Actions tab

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Run fetch script
        run: python fetch_scholar.py

      - name: Commit and push updated data.json
        run: |
          echo "Current git status:"
          git status
          echo "Configuring git user..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "Adding data.json to staging..."
          git add data.json || true
          echo "Checking for changes to commit..."
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            echo "Changes detected, committing..."
            git commit -m "chore: update scholar stats (automated)"
            echo "Pushing changes to repository..."
            git push origin main
            echo "Successfully pushed changes"
          fi
